import { StyleSheet } from 'react-native-unistyles'

export const styles = StyleSheet.create((theme) => ({
  message: (isMe: boolean) => ({
    maxWidth: '82%',
    borderRadius: theme.radius.lg,
    alignSelf: isMe ? 'flex-end' : 'flex-start',
    borderCurve: 'continuous',
    zIndex: 10,
    minHeight: 42,
    backgroundColor: isMe ? theme.colors.primary : theme.colors.foreground,
  }),
  messageWrapper: (isMe: boolean, marginBottom) => ({
    gap: theme.spacing.md,
    position: 'relative',
    justifyContent: 'center',
    marginBottom,
    alignItems: isMe ? 'flex-end' : 'flex-start',
  }),
  messageContent: {
    paddingHorizontal: theme.spacing.lg,
    padding: theme.spacing.md - 1,
    minHeight: 42,
    flexDirection: 'row',
    position: 'relative',
  },
  text: (isMe: boolean) => ({
    fontSize: theme.fontSize.md,
    fontFamily: theme.fontFamily.regular,
    color: isMe ? theme.colors.white : theme.colors.text,
  }),
  secondaryText: (isMe: boolean) => ({
    fontSize: theme.fontSize.xs,
    fontFamily: theme.fontFamily.medium,
    position: 'absolute',
    right: theme.spacing.md + 2,
    bottom: theme.spacing.sm,
    color: isMe ? theme.colors.white : theme.colors.secondaryText,
    opacity: isMe ? theme.opacity.contentText : 1,
  }),
  timeSpacer: {
    width: 38,
    height: 14,
    marginRight: -theme.spacing.lg,
  },
  statusCanvas: (height: number) => ({
    height,
    left: 0,
    right: 0,
    backgroundColor: 'transparent',
    marginRight: -16,
    position: 'absolute',
  }),
  statusBubble: (isMe: boolean) => ({
    backgroundColor: isMe ? theme.colors.primary : theme.colors.foreground,
    borderRadius: theme.radius.full,
    width: 8,
    opacity: theme.opacity.contentText,
    right: -6,
    height: 8,
    position: 'absolute',
  }),
  statusBubbleEffect: (isMe: boolean) => ({
    backgroundColor: isMe ? theme.colors.primary : theme.colors.foreground,
    borderRadius: theme.radius.full,
    width: 8,
    transformOrigin: 'center',
    opacity: theme.opacity.contentText,
    right: -6,
    height: 8,
    position: 'absolute',
  }),
}))
