export const EMOJI_AVATARS = {
	a: { emoji: require("@assets/avatars/🤩.webp"), color: "#FFB56659" },
	b: { emoji: require("@assets/avatars/🐸.webp"), color: "#6FAA6859" },
	c: { emoji: require("@assets/avatars/🐈.webp"), color: "#BA6E3559" },
	d: { emoji: require("@assets/avatars/🐵.webp"), color: "#D7B18159" },
	e: { emoji: require("@assets/avatars/💸.webp"), color: "#E4E2D059" },
	f: { emoji: require("@assets/avatars/🍓.webp"), color: "#AE1C1E59" },
	g: { emoji: require("@assets/avatars/🍌.webp"), color: "#E9AC0759" },
	h: { emoji: require("@assets/avatars/😶‍🌫️.webp"), color: "#DCDCCC59" },
	i: { emoji: require("@assets/avatars/😹.webp"), color: "#FFD77059" },
	j: { emoji: require("@assets/avatars/🦓.webp"), color: "#6E686259" },
	k: { emoji: require("@assets/avatars/🍆.webp"), color: "#A3699E59" },
	l: { emoji: require("@assets/avatars/🥵.webp"), color: "#EC510859" },
	m: { emoji: require("@assets/avatars/💀.webp"), color: "#C7C7C559" },
	n: { emoji: require("@assets/avatars/👽.webp"), color: "#97A6A759" },
	o: { emoji: require("@assets/avatars/☹️.webp"), color: "#FFBC2E59" },
	p: { emoji: require("@assets/avatars/😎.webp"), color: "#FFBC2E59" },
	q: { emoji: require("@assets/avatars/😈.webp"), color: "#A13CB659" },
	r: { emoji: require("@assets/avatars/🤖.webp"), color: "#5D949C59" },
	s: { emoji: require("@assets/avatars/🎃.webp"), color: "#F29A0B59" },
	t: { emoji: require("@assets/avatars/🍎.webp"), color: "#E5262859" },
	u: { emoji: require("@assets/avatars/🍅.webp"), color: "#E04B2259" },
	v: { emoji: require("@assets/avatars/🥑.webp"), color: "#BDC95159" },
	w: { emoji: require("@assets/avatars/⚽.webp"), color: "#50505059" },
	x: { emoji: require("@assets/avatars/🥺.webp"), color: "#FFBC2E59" },
	y: { emoji: require("@assets/avatars/💪.webp"), color: "#FFBC2E59" },
	z: { emoji: require("@assets/avatars/🦷.webp"), color: "#D4C8B659" },
	_: { emoji: require("@assets/avatars/👀.webp"), color: "#602F0059" },
	"-": { emoji: require("@assets/avatars/🧠.webp"), color: "#FD97B759" },
} as const;
